DROP DATABASE NPANEL;

CREATE DATABASE IF NOT EXISTS NPANEL;
USE NPANEL;

CREATE TABLE ESTATS(
ID_ESTAT INT AUTO_INCREMENT PRIMARY KEY,
ESTAT VARCHAR(200)
);

CREATE TABLE CATEGORIES(
ID_CATEGORIA INT AUTO_INCREMENT PRIMARY KEY,
CATEGORIA VARCHAR(200),
PREFIX VARCHAR(200),
DATA_INICI DATE,
DATA_FI DATE,
ID_ESTAT INT REFERENCES ESTATS (ID_ESTAT)
);

CREATE TABLE USUARIS (
ID_USUARI INT AUTO_INCREMENT PRIMARY KEY,
CONTRASENYA VARCHAR(200),
EMAIL VARCHAR(200),
NOM VARCHAR(200),
COGNOMS VARCHAR(200),
FOTO BLOB,
SEXE ENUM('Masculí', 'Femení'),
DATA_NAIXEMENT DATE,
ROL ENUM('NEDADOR', 'ENTRENADOR', 'ADMINISTRADOR'),
VALIDAT ENUM('SI', 'NO'),
ID_ESTAT INT REFERENCES ESTATS (ID_ESTAT),
ID_CATEGORIA INT REFERENCES CATEGORIES (ID_CATEGORIA)
);

CREATE TABLE COMPETICIONS (
ID_COMPETICIO INT AUTO_INCREMENT,
COMPETICIO VARCHAR(200),
DATA_HORA_1 TIMESTAMP,
DATA_HORA_2 TIMESTAMP,
LLOC VARCHAR(200),
RESULTATS VARCHAR (200),
ID_CALENDARI VARCHAR(100),
ID_ESTAT INT REFERENCES ESTATS (ID_ESTAT),
ID_CATEGORIA INT REFERENCES CATEGORIES (ID_CATEGORIA),
PRIMARY KEY (ID_COMPETICIO, ID_ESTAT, ID_CATEGORIA)
);

CREATE TABLE PARTICIPACIONS (
ID_USUARI INT,
ID_COMPETICIO INT,
ID_ESTAT INT,
ID_CATEGORIA INT,
PRIMARY KEY (ID_USUARI, ID_COMPETICIO, ID_ESTAT, ID_CATEGORIA)
);

CREATE TABLE ACTUALITAT(
ID_BLOG INT AUTO_INCREMENT PRIMARY KEY,
TITOL VARCHAR(200),
DATA_PUBLICACIO DATE,
COMENTARI VARCHAR(1000),
FOTO BLOB 	
);


CREATE TABLE DOCUMENTS (
	ID_DOCUMENT INT AUTO_INCREMENT PRIMARY KEY,
	TITUL VARCHAR (200),
	DOCUMENT VARCHAR(200)
	);

CREATE TABLE URLS (
	ID_ENLLAS INT AUTO_INCREMENT PRIMARY KEY,
	TITUL VARCHAR (200),
	URL VARCHAR(200)
	);

CREATE TABLE GALERIES (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	NOM VARCHAR (200),
	URL VARCHAR(300)
	);

CREATE TABLE FOTOS (
	ID_FOTO INT AUTO_INCREMENT,
	NOM VARCHAR (200),
	URL VARCHAR(300),
	ID_GALERIA INT REFERENCES GALERIES(NOM) ON DELETE CASCADE,
	PRIMARY KEY ( ID_FOTO, ID_GALERIA)
	);

CREATE TABLE HIST_ACTUALITAT(
HIST_ACTUALITAT INT PRIMARY KEY,
ID_USUARI INT REFERENCES USUARIS (ID_USUARI),
DATA_PUBLICACIO DATE,
ACCIO VARCHAR(200)
);

CREATE TABLE HIST_COMPETICIONS(
HIST_COMPETICIONS INT PRIMARY KEY,
ID_USUARI INT REFERENCES USUARIS (ID_USUARI),
DATA_PUBLICACIO DATE,
ACCIO VARCHAR(200)
);

CREATE TABLE HIST_DOCUMENTS(
HIST_DOCUMENTS INT PRIMARY KEY,
ID_USUARI INT REFERENCES USUARIS (ID_USUARI),
DATA_PUBLICACIO DATE,
ACCIO VARCHAR(200)
);

CREATE TABLE HIST_URLS(
HIST_URLS INT PRIMARY KEY,
ID_USUARI INT REFERENCES USUARIS (ID_USUARI),
DATA_PUBLICACIO DATE,
ACCIO VARCHAR(200)
);

CREATE TABLE HIST_GALERIES(
HIST_GALERIES INT PRIMARY KEY,
ID_USUARI INT REFERENCES USUARIS (ID_USUARI),
DATA_PUBLICACIO DATE,
ACCIO VARCHAR(200)
);

CREATE TABLE HIST_USUARIS(
HIST_USUARIS INT PRIMARY KEY,
ID_USUARI INT REFERENCES USUARIS (ID_USUARI),
DATA_PUBLICACIO DATE,
ACCIO VARCHAR(200)
);

CREATE TABLE HIST_ESTATS(
HIST_ESTATS INT PRIMARY KEY,
ID_USUARI INT,
DATA_PUBLICACIO DATE,
ACCIO VARCHAR(200)
);

CREATE TABLE HIST_CATEGORIES(
HIST_CATEGORIES INT PRIMARY KEY,
ID_USUARI INT REFERENCES USUARIS (ID_USUARI),
DATA_PUBLICACIO DATE,
ACCIO VARCHAR(200)
);
